  spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        menu-in:
          destination: x
          contentType: application/json
        menu-out:
          destination: x
          contentType: application/json
          